#pragma once

void isr_default (void);

// system irq
void isr_nmi (void)                    __attribute__((weak, alias ("isr_default")));
void isr_hardfault (void)              __attribute__((weak, alias ("isr_default")));
void isr_memmanage (void)              __attribute__((weak, alias ("isr_default")));
void isr_busfault (void)               __attribute__((weak, alias ("isr_default")));
void isr_usagefault (void)             __attribute__((weak, alias ("isr_default")));
void isr_svcall (void)                 __attribute__((weak, alias ("isr_default")));
void isr_debugmonitor (void)           __attribute__((weak, alias ("isr_default")));
void isr_pendsv (void)                 __attribute__((weak, alias ("isr_default")));
void isr_systick (void)                __attribute__((weak, alias ("isr_default")));

// irq
void isr_wwdg (void)                   __attribute__((weak, alias ("isr_default")));
void isr_pvd (void)                    __attribute__((weak, alias ("isr_default")));
void isr_tamper (void)                 __attribute__((weak, alias ("isr_default")));
void isr_rtc (void)                    __attribute__((weak, alias ("isr_default")));
void isr_flash (void)                  __attribute__((weak, alias ("isr_default")));
void isr_rcc (void)                    __attribute__((weak, alias ("isr_default")));
void isr_exti0 (void)                  __attribute__((weak, alias ("isr_default")));
void isr_exti1 (void)                  __attribute__((weak, alias ("isr_default")));
void isr_exti2 (void)                  __attribute__((weak, alias ("isr_default")));
void isr_exti3 (void)                  __attribute__((weak, alias ("isr_default")));
void isr_exti4 (void)                  __attribute__((weak, alias ("isr_default")));
void isr_dma1_channel1 (void)          __attribute__((weak, alias ("isr_default")));
void isr_dma1_channel2 (void)          __attribute__((weak, alias ("isr_default")));
void isr_dma1_channel3 (void)          __attribute__((weak, alias ("isr_default")));
void isr_dma1_channel4 (void)          __attribute__((weak, alias ("isr_default")));
void isr_dma1_channel5 (void)          __attribute__((weak, alias ("isr_default")));
void isr_dma1_channel6 (void)          __attribute__((weak, alias ("isr_default")));
void isr_dma1_channel7 (void)          __attribute__((weak, alias ("isr_default")));
void isr_adc1_2 (void)                 __attribute__((weak, alias ("isr_default")));
void isr_usb_hp_can_tx (void)          __attribute__((weak, alias ("isr_default")));
void isr_usb_lp_can_rx0 (void)         __attribute__((weak, alias ("isr_default")));
void isr_can_rx1 (void)                __attribute__((weak, alias ("isr_default")));
void isr_can_sce (void)                __attribute__((weak, alias ("isr_default")));
void isr_exti9_5 (void)                __attribute__((weak, alias ("isr_default")));
void isr_tim1_brk (void)               __attribute__((weak, alias ("isr_default")));
void isr_tim1_up (void)                __attribute__((weak, alias ("isr_default")));
void isr_tim1_trg_com (void)           __attribute__((weak, alias ("isr_default")));
void isr_tim1_cc (void)                __attribute__((weak, alias ("isr_default")));
void isr_tim2 (void)                   __attribute__((weak, alias ("isr_default")));
void isr_tim3 (void)                   __attribute__((weak, alias ("isr_default")));
void isr_tim4 (void)                   __attribute__((weak, alias ("isr_default")));
void isr_i2c1_ev (void)                __attribute__((weak, alias ("isr_default")));
void isr_i2c1_er (void)                __attribute__((weak, alias ("isr_default")));
void isr_i2c2_ev (void)                __attribute__((weak, alias ("isr_default")));
void isr_i2c2_er (void)                __attribute__((weak, alias ("isr_default")));
void isr_spi1 (void)                   __attribute__((weak, alias ("isr_default")));
void isr_spi2 (void)                   __attribute__((weak, alias ("isr_default")));
void isr_usart1 (void)                 __attribute__((weak, alias ("isr_default")));
void isr_usart2 (void)                 __attribute__((weak, alias ("isr_default")));
void isr_usart3 (void)                 __attribute__((weak, alias ("isr_default")));
void isr_exti15_10 (void)              __attribute__((weak, alias ("isr_default")));
void isr_rtcalarm (void)               __attribute__((weak, alias ("isr_default")));
void isr_usbwakeup (void)              __attribute__((weak, alias ("isr_default")));
void isr_tim8_brk (void)               __attribute__((weak, alias ("isr_default")));
void isr_tim8_up (void)                __attribute__((weak, alias ("isr_default")));
void isr_tim8_trg_com (void)           __attribute__((weak, alias ("isr_default")));
void isr_tim8_cc (void)                __attribute__((weak, alias ("isr_default")));
void isr_adc3 (void)                   __attribute__((weak, alias ("isr_default")));
void isr_fsmc (void)                   __attribute__((weak, alias ("isr_default")));
void isr_sdio (void)                   __attribute__((weak, alias ("isr_default")));
void isr_tim5 (void)                   __attribute__((weak, alias ("isr_default")));
void isr_spi3 (void)                   __attribute__((weak, alias ("isr_default")));
void isr_uart4 (void)                  __attribute__((weak, alias ("isr_default")));
void isr_uart5 (void)                  __attribute__((weak, alias ("isr_default")));
void isr_tim6 (void)                   __attribute__((weak, alias ("isr_default")));
void isr_tim7 (void)                   __attribute__((weak, alias ("isr_default")));
void isr_dma2_channel1 (void)          __attribute__((weak, alias ("isr_default")));
void isr_dma2_channel2 (void)          __attribute__((weak, alias ("isr_default")));
void isr_dma2_channel3 (void)          __attribute__((weak, alias ("isr_default")));
void isr_dma2_channel4_5(void)         __attribute__((weak, alias ("isr_default")));
